CREATE USER ESTUDIANTE PASSWORD 'estudiante';

CREATE ROLE R_ESTUDIANTE;

GRANT SELECT ON NOTA TO R_ESTUDIANTE;
GRANT SELECT ON ASIGNATURA TO R_ESTUDIANTE;
GRANT UPDATE (correo) ON USUARIO TO R_ESTUDIANTE;


CREATE USER DOCENTE PASSWORD 'docente';

CREATE ROLE R_DOCENTE;

GRANT SELECT ON NOTA TO R_DOCENTE;
GRANT SELECT ON ASIGNATURA TO R_DOCENTE;
GRANT UPDATE (correo) ON USUARIO TO R_DOCENTE;
GRANT INSERT ON NOTAS TO R_DOCENTE;
